cert:
    dir: /Users/trump/Projects/edge/edge-node/cert
    validity-days: 90
    renew-days: 2
zerossl:
    api-key: ""
    base-url: https://api.zerossl.com
s3:
    endpoint: ""
    access-key: ""
    secret: ""
    region: auto
    bucket: ""
public_ips: []
app_names: []

